

#         Powered by TabooLib 6.0         #

database:

  # 数据存储方式
  # YAML(默认), MySQL
  storage: YAML

  # 数据源配置
  source:

    # MySQL相关设置
    mysql:
      host: localhost
      port: 3306
      user: root
      password: 12345
      database: minecraft
      table-prefix: aiurtitle_

title-setting:

  # 默认称号设置
  default:

    # 前缀
    prefix: '&f['

    # 后缀
    suffix: '&f]'

    # 显示称号
    display: '&7平民'
    description:
      - '我是简介'
    icon:
      template: 'default'

template-setting:

  # 当上述默认模板无法正常被加载时
  # 使用一下的模板，默认id为 default
  default:
    display:
      mat: 'Name_Tag'
      name: '${display-title}'
      lore:
        - '&f&l>>&a&l Description'
        - ' &c&lo &7{{description}}'
        - ''
        - '{{button}}'
      shiny: 'false'
    script:
      button: 'if check $menu-type is *shop then $button-repository else $button-shop'
    properties:
      button-repository: 'Use Now'
      button-shop: 'Acquire Now'